# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='item.proto',
  package='tutorial',
  serialized_pb='\n\nitem.proto\x12\x08tutorial\",\n\x10PGDBInstanceData\x12\x0b\n\x03idx\x18\x01 \x02(\r\x12\x0b\n\x03val\x18\x02 \x02(\r\"%\n\tPGDBInlay\x12\x0b\n\x03idx\x18\x01 \x02(\r\x12\x0b\n\x03val\x18\x02 \x02(\r\"4\n\x0cPGDBAttrNode\x12\x0b\n\x03idx\x18\x01 \x02(\r\x12\n\n\x02id\x18\x02 \x02(\r\x12\x0b\n\x03val\x18\x03 \x02(\x02\"\xcc\x03\n\x08PGDBItem\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x10\n\x08\x63lass_id\x18\x02 \x02(\r\x12\x0e\n\x06number\x18\x03 \x02(\r\x12\x0c\n\x04slot\x18\x04 \x02(\r\x12\x11\n\tendurance\x18\x05 \x02(\r\x12\r\n\x05usage\x18\x06 \x02(\r\x12\x0f\n\x07statbuf\x18\x07 \x02(\r\x12\x11\n\ttime_type\x18\x08 \x02(\r\x12\x10\n\x08reserved\x18\t \x02(\r\x12\x12\n\nstart_time\x18\n \x02(\r\x12\x10\n\x08\x65nd_time\x18\x0b \x02(\r\x12#\n\x06inlays\x18\x0c \x03(\x0b\x32\x13.tutorial.PGDBInlay\x12\x31\n\rinstance_data\x18\r \x03(\x0b\x32\x1a.tutorial.PGDBInstanceData\x12,\n\x0cinlays_attrs\x18\x0e \x03(\x0b\x32\x16.tutorial.PGDBAttrNode\x12)\n\tbase_attr\x18\x0f \x03(\x0b\x32\x16.tutorial.PGDBAttrNode\x12)\n\trand_attr\x18\x10 \x03(\x0b\x32\x16.tutorial.PGDBAttrNode\x12*\n\ntitle_attr\x18\x11 \x03(\x0b\x32\x16.tutorial.PGDBAttrNode\"/\n\x0bPGDBItemSet\x12 \n\x04item\x18\x01 \x03(\x0b\x32\x12.tutorial.PGDBItemB\x14\n\x0c\x63om.tg.protoB\x04Item')




_PGDBINSTANCEDATA = _descriptor.Descriptor(
  name='PGDBInstanceData',
  full_name='tutorial.PGDBInstanceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx', full_name='tutorial.PGDBInstanceData.idx', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='tutorial.PGDBInstanceData.val', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=68,
)


_PGDBINLAY = _descriptor.Descriptor(
  name='PGDBInlay',
  full_name='tutorial.PGDBInlay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx', full_name='tutorial.PGDBInlay.idx', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='tutorial.PGDBInlay.val', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=70,
  serialized_end=107,
)


_PGDBATTRNODE = _descriptor.Descriptor(
  name='PGDBAttrNode',
  full_name='tutorial.PGDBAttrNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx', full_name='tutorial.PGDBAttrNode.idx', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='tutorial.PGDBAttrNode.id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='tutorial.PGDBAttrNode.val', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=109,
  serialized_end=161,
)


_PGDBITEM = _descriptor.Descriptor(
  name='PGDBItem',
  full_name='tutorial.PGDBItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tutorial.PGDBItem.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='class_id', full_name='tutorial.PGDBItem.class_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number', full_name='tutorial.PGDBItem.number', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slot', full_name='tutorial.PGDBItem.slot', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='endurance', full_name='tutorial.PGDBItem.endurance', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usage', full_name='tutorial.PGDBItem.usage', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statbuf', full_name='tutorial.PGDBItem.statbuf', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_type', full_name='tutorial.PGDBItem.time_type', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reserved', full_name='tutorial.PGDBItem.reserved', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='tutorial.PGDBItem.start_time', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='tutorial.PGDBItem.end_time', index=10,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inlays', full_name='tutorial.PGDBItem.inlays', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance_data', full_name='tutorial.PGDBItem.instance_data', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inlays_attrs', full_name='tutorial.PGDBItem.inlays_attrs', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='base_attr', full_name='tutorial.PGDBItem.base_attr', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rand_attr', full_name='tutorial.PGDBItem.rand_attr', index=15,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title_attr', full_name='tutorial.PGDBItem.title_attr', index=16,
      number=17, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=164,
  serialized_end=624,
)


_PGDBITEMSET = _descriptor.Descriptor(
  name='PGDBItemSet',
  full_name='tutorial.PGDBItemSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='tutorial.PGDBItemSet.item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=626,
  serialized_end=673,
)

_PGDBITEM.fields_by_name['inlays'].message_type = _PGDBINLAY
_PGDBITEM.fields_by_name['instance_data'].message_type = _PGDBINSTANCEDATA
_PGDBITEM.fields_by_name['inlays_attrs'].message_type = _PGDBATTRNODE
_PGDBITEM.fields_by_name['base_attr'].message_type = _PGDBATTRNODE
_PGDBITEM.fields_by_name['rand_attr'].message_type = _PGDBATTRNODE
_PGDBITEM.fields_by_name['title_attr'].message_type = _PGDBATTRNODE
_PGDBITEMSET.fields_by_name['item'].message_type = _PGDBITEM
DESCRIPTOR.message_types_by_name['PGDBInstanceData'] = _PGDBINSTANCEDATA
DESCRIPTOR.message_types_by_name['PGDBInlay'] = _PGDBINLAY
DESCRIPTOR.message_types_by_name['PGDBAttrNode'] = _PGDBATTRNODE
DESCRIPTOR.message_types_by_name['PGDBItem'] = _PGDBITEM
DESCRIPTOR.message_types_by_name['PGDBItemSet'] = _PGDBITEMSET

class PGDBInstanceData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PGDBINSTANCEDATA

  # @@protoc_insertion_point(class_scope:tutorial.PGDBInstanceData)

class PGDBInlay(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PGDBINLAY

  # @@protoc_insertion_point(class_scope:tutorial.PGDBInlay)

class PGDBAttrNode(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PGDBATTRNODE

  # @@protoc_insertion_point(class_scope:tutorial.PGDBAttrNode)

class PGDBItem(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PGDBITEM

  # @@protoc_insertion_point(class_scope:tutorial.PGDBItem)

class PGDBItemSet(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PGDBITEMSET

  # @@protoc_insertion_point(class_scope:tutorial.PGDBItemSet)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\014com.tg.protoB\004Item')
# @@protoc_insertion_point(module_scope)
